// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": process.env.aws_project_region,
    "aws_cognito_identity_pool_id": process.env.aws_cognito_identity_pool_id,
    "aws_cognito_region": process.env.aws_cognito_region,
    "aws_user_pools_id": process.env.aws_user_pools_id,
    "aws_user_pools_web_client_id": process.env.aws_user_pools_web_client_id,
    "aws_appsync_graphqlEndpoint": process.env.aws_appsync_graphqlEndpoint,,
    "aws_appsync_region": process.env.aws_appsync_region,
    "aws_appsync_authenticationType": process.env.aws_appsync_authenticationType
};

export default awsmobile;
