// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e9b8129c-593f-4934-ac14-7d080a2b28c4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_eP0uEYgbB",
    "aws_user_pools_web_client_id": "7ptuaqep11ijob2r0kbm3jl92i",
    "aws_appsync_graphqlEndpoint": "https://kwfyc2y3kva5bpxbdxgbz345pa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
